spring:
  main:
    banner-mode: "off"

dev:
  matelang:
    orchestrator:
      k8s-client:
        kubeconfig: "/home/mate/.kube/config"
        config:
          basePath: "https://localhost"
          ca: ""
          auth:
            accessToken: ""
            username: ""
            password: ""
            clientcert:
              cert: ""
              key: ""